# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.require_version ">= 1.6.5"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Using Puppet Labs official vagrant boxes, from: https://vagrantcloud.com/puppetlabs
  config.vm.box = "puppetlabs/centos-6.6-64-puppet"
#config.vm.provision :shell, inline: 'wget --no-check-certificate https://github.com/aglover/ubuntu-equip/raw/master/equip_java7_64.sh && bash equip_java7_64.sh'

  config.vm.provision :shell, :path => "./.vagrant_puppet/init.sh"
#  config.vm.provision "fix-no-tty", type: "shell" do |s|
#      s.privileged = false
#          s.inline = "sudo sed -i '/tty/!s/mesg n/tty -s \\&\\& mesg n/' /root/.profile"
#  end
  config.vm.provision :puppet do |puppet|
#  puppet.manifests_path= "/Users/nishantk/nishant_project/rtbrtusu/manifests"
#    puppet.manifest_file  = "init.pp"
    
 puppet.manifests_path = "./.vagrant_puppet"
 puppet.manifest_file  = "init.pp"
    puppet.options = "--verbose"
  end

end
